version: "3"
services:
  influxdb:
    image: influxdb:1.8.2
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always
    environment:
      - INFLUXDB_DB=strava
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - "8086:8086"
    networks:
      - fit-network
  grafana:
    image: grafana/grafana
    networks:
      - fit-network
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning

    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

  pythonpower:
    image: fit-file-parser
    depends_on:
      - influxdb
      - grafana
    
    networks:
      - fit-network

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  fit-network:
    driver: bridge
